const express = require('express');
const cors = require('cors');
require('dotenv').config();
const path = require('path');

const authRoutes = require('./routes/administracion/authRoutes');
const menuRoutes = require('./routes/menuRoutes');
const empresaRoutes = require('./routes/administracion/empresaRoutes');
const usuarioRoutes = require('./routes/administracion/usuarioRoutes');
const perfilRoutes = require('./routes/administracion/perfilRoutes');
const permisoRoutes = require('./routes/administracion/permisoRoutes');
const geografiaRoutes = require('./routes/administracion/geografiaRoutes');
const secuenciaRoutes = require('./routes/administracion/secuenciaRoutes');
const periodoRoutes = require('./routes/administracion/periodoRoutes');
const catalogoRoutes = require('./routes/administracion/catalogoRoutes');
const monedaRoutes = require('./routes/administracion/monedaRoutes');
const departamentoRoutes = require('./routes/recursos_humanos/departamentoRoutes');
const centroCostoRoutes = require('./routes/recursos_humanos/centroCostoRoutes');
const propositoRoutes = require('./routes/administracion/propositoRoutes');
const unidadMedidaRoutes = require('./routes/administracion/unidadMedidaRoutes');
const conversionUnidadesRoutes = require('./routes/administracion/conversionUnidadesRoutes');
const cargoRoutes = require('./routes/recursos_humanos/cargoRoutes');
const solicitudRoutes = require('./routes/recursos_humanos/solicitudRoutes');
const infoComplementariaRoutes = require('./routes/recursos_humanos/infoComplementariaRoutes');
const dependienteRoutes = require('./routes/recursos_humanos/dependienteRoutes');
const educacionRoutes = require('./routes/recursos_humanos/educacionRoutes');
const idiomaRoutes = require('./routes/recursos_humanos/idiomaRoutes');
const experienciaRoutes = require('./routes/recursos_humanos/experienciaRoutes');
const referenciaRoutes = require('./routes/recursos_humanos/referenciaRoutes');
const otrosRoutes = require('./routes/recursos_humanos/otrosRoutes');
const grupoOcupacionalRoutes = require('./routes/recursos_humanos/grupoOcupacionalRoutes');
const cedeRoutes = require('./routes/recursos_humanos/cedeRoutes');
const tipoAccionRoutes = require('./routes/administracion/tipoAccionRoutes');
const turnoRoutes = require('./routes/recursos_humanos/turnoRoutes');
const direccionRoutes = require('./routes/administracion/direccionRoutes');
const dependenciaRoutes = require('./routes/recursos_humanos/dependenciaRoutes');
const dependenciaCargoRoutes = require('./routes/recursos_humanos/dependenciaCargoRoutes');
const tipoNominaRoutes = require('./routes/nomina/tipoNominaRoutes');
const designacionRoutes = require('./routes/recursos_humanos/designacionRoutes');
const parametrosRoutes = require('./routes/administracion/parametrosRoutes');
const empleadoRoutes = require('./routes/recursos_humanos/empleadoRoutes');
const empleadoTiempoRoutes = require('./routes/recursos_humanos/empleadoTiempoRoutes');
const actualizaBancoRoutes = require('./routes/recursos_humanos/actualizaBancoRoutes');
const actualizaSalarioRoutes = require('./routes/recursos_humanos/actualizaSalarioRoutes');
const empleadoNominaRoutes = require('./routes/nomina/empleadoNominaRoutes');
const tipoTransaccionRoutes = require('./routes/nomina/tipoTransaccionRoutes');
const empleadoDependienteRoutes = require('./routes/recursos_humanos/empleadoDependienteRoutes');
const isrRoutes = require('./routes/administracion/isrRoutes');
const afparsRoutes = require('./routes/administracion/afparsRoutes');
const periodosNominasRoutes = require('./routes/nomina/periodosNominasRoutes');
const abrirNominaRoutes = require('./routes/nomina/abrirNominaRoutes');
const generarNominaRoutes = require('./routes/nomina/generarNominaRoutes');
const transaccionesEmpleadoRoutes = require('./routes/recursos_humanos/transaccionesEmpleadoRoutes');
const subirNominaExcelRoutes = require('./routes/nomina/subirNominaExcelRoutes');
const aplicarDescuentosRoutes = require('./routes/nomina/aplicarDescuentosRoutes');
const cerrarNominaRoutes = require('./routes/nomina/cerrarNominaRoutes');
const parametrosNominaRoutes = require('./routes/nomina/parametrosNominaRoutes');
const archivoBancoRoutes = require('./routes/nomina/archivoBancoRoutes');
const cambiosRoutes = require('./routes/recursos_humanos/cambiosRoutes');

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

// Serve static uploads
app.use('/uploads', express.static(path.join(__dirname, '../uploads')));

// Routes
app.use('/api/auth', authRoutes);
app.use('/api/menu', menuRoutes);
app.use('/api/empresas', empresaRoutes);
app.use('/api/usuarios', usuarioRoutes);
app.use('/api/perfiles', perfilRoutes);
app.use('/api/permisos', permisoRoutes);
app.use('/api/geografia', geografiaRoutes);
app.use('/api/secuencias', secuenciaRoutes);
app.use('/api/periodos', periodoRoutes);
app.use('/api/catalogo', catalogoRoutes);
app.use('/api/monedas', monedaRoutes);
app.use('/api/departamentos', departamentoRoutes);
app.use('/api/centro-costos', centroCostoRoutes);
app.use('/api/propositos', propositoRoutes);
app.use('/api/unidades-medida', unidadMedidaRoutes);
app.use('/api/conversion-unidades', conversionUnidadesRoutes);
app.use('/api/cargos', cargoRoutes);
app.use('/api/solicitudes', solicitudRoutes);
app.use('/api/info/parentescos', infoComplementariaRoutes.parentescosRouter);
app.use('/api/info/niveles-academicos', infoComplementariaRoutes.nivelesAcademicosRouter);
app.use('/api/info/titulos-academicos', infoComplementariaRoutes.titulosAcademicosRouter);
app.use('/api/info/idiomas', infoComplementariaRoutes.idiomasRouter);
app.use('/api/info/traducciones', infoComplementariaRoutes.traduccionesRouter);
app.use('/api/info/actividades', infoComplementariaRoutes.actividadesRouter);
app.use('/api/dependientes', dependienteRoutes);
app.use('/api/educacion', educacionRoutes);
app.use('/api/idiomas', idiomaRoutes);
app.use('/api/experiencia', experienciaRoutes);
app.use('/api/referencias', referenciaRoutes);
app.use('/api/otros', otrosRoutes);
app.use('/api/configuracion/grupos-ocupacionales', grupoOcupacionalRoutes);
app.use('/api/configuracion/cedes', cedeRoutes);
app.use('/api/configuracion/tipos-acciones', tipoAccionRoutes);
app.use('/api/configuracion/clasificaciones', require('./routes/configuracion/clasificacionRoutes'));
app.use('/api/configuracion/turnos', turnoRoutes);
app.use('/api/configuracion/direcciones', direccionRoutes);
app.use('/api/configuracion/direcciones/:direccionId/dependencias', dependenciaRoutes);
app.use('/api/configuracion/dependencias/:dependenciaId/cargos', dependenciaCargoRoutes);
app.use('/api/configuracion/tipos-nominas', tipoNominaRoutes);
app.use('/api/configuracion/parametros-rrhh', parametrosRoutes);
app.use('/api/designaciones', designacionRoutes);
app.use('/api/cambios', cambiosRoutes);
app.use('/api/separacion', require('./routes/recursos_humanos/separacionRoutes'));
app.use('/api/amonestaciones', require('./routes/recursos_humanos/amonestacionRoutes'));
app.use('/api/vacaciones', require('./routes/recursos_humanos/vacacionRoutes'));
app.use('/api/ausencias', require('./routes/recursos_humanos/ausencias'));
app.use('/api/empleados', empleadoRoutes);
app.use('/api/empleado-tiempo', empleadoTiempoRoutes);
app.use('/api/actualiza-banco', actualizaBancoRoutes);
app.use('/api/actualiza-salario', actualizaSalarioRoutes);
app.use('/api/empleado-nomina', empleadoNominaRoutes);
app.use('/api/tipos-transacciones', tipoTransaccionRoutes);
app.use('/api/empleados-dependientes', empleadoDependienteRoutes);
app.use('/api/isr', isrRoutes);
app.use('/api/afpars', afparsRoutes);
app.use('/api/periodos-nominas', periodosNominasRoutes);
app.use('/api/abrir-nomina', abrirNominaRoutes);
app.use('/api/generar-nomina', generarNominaRoutes);
app.use('/api/transacciones-empleados', transaccionesEmpleadoRoutes);
app.use('/api/subir-nomina-excel', subirNominaExcelRoutes);
app.use('/api/aplicar-descuentos', aplicarDescuentosRoutes);
app.use('/api/cerrar-nomina', cerrarNominaRoutes);
app.use('/api/nomina/parametros', parametrosNominaRoutes);
app.use('/api/archivo-banco', archivoBancoRoutes);
app.use('/api/cambios', cambiosRoutes);

// Health check
app.get('/api/health', (req, res) => {
    res.json({ status: 'API is running' });
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});

